MMAX_WORD_TAG = 'word'
MMAX_WORDS_TAG = 'words'
MMAX_WORD_NUMBER_ATTRIBUTE = 'alppos'
MMAX_WORDS_DOCUMENT_ID_ATTRIBUTE = 'alpsent'
MMAX_WORDS_DOCUMENT_ID_POSTFIX = '_words.xml'
MMAX_SENTENCE_STARTING_WORD_NUMBER = '0'    # This **must** be a string
